[package]
name = "frogger"
version = "0.1.0"
edition = "2021"

[dependencies]
# I'm glad you came to add the `log` dependency! I got it all ready for you, just uncomment:
#
log = "0.4"
env_logger = "0.9"
